### PR TITLE
Allow CSV imports from stdin

### PR DESCRIPTION
**Pull request by odarbelaeze**
This PR allows you to do:

```shell
tt load-csv -
```

And therefore allows for interoperability with https://github.com/odarbelaeze/codelog, this allows you to do:

```shell
codelog report | tt load-csv -
```

or with an optional date:

```shell
codelog report Dec 17 | tt load-csv -
```

### CODE REVIEW

**Review by fboaventura — APPROVED** [review]

**Review by fboaventura — CHANGES_REQUESTED** [review]
You've touched practically all the code with cosmetics changes.  Can you replace back the `"` by `'` and the formatting?  It will make it easier to track and identify the structural changes and make the commit aligned with the actual changes. :smiley:

**Comment by odarbelaeze** [comment]
@fboaventura re-did the PR with code formatting disabled. I did relax some requirements for better compatibility with the new `pip`.

**Comment by eyscode** [comment]
@fboaventura what is the status of this PR after @odarbelaeze last update? Is something else required?

**Comment by eyscode** [comment]
@odarbelaeze can you resolve the conflicts? besides that @fboaventura what is the status of this PR after @odarbelaeze last update? Is something else asked to address?

**Comment by fboaventura** [comment]
@eyscode @odarbelaeze nothing else to address, just the conflicts.

**Comment by odarbelaeze** [comment]
@fboaventura fixed conflicts.

**Comment by eyscode** [comment]
Cool 🎉. Both folks were invited to Pypi project, so feel free to update CHANGELOG.md, README.md and release a new version. @odarbelaeze @fboaventura

**Pull request merged**
