### PR TITLE
Load csv file to tt

### PR DESCRIPTION
**Pull request by diegotolentino**
Allow load csv file like this:

date,hours,text
16/06/2020,0.5,All your base are belong to us

with the command:
`tt load-csv ~/Path/to/file.csv`

### CODE REVIEW

**Comment by eyscode** [comment]
Nice feature! I cannot test this since I'm not BairesDev employee anymore, as soon I transfer this repository to a colleague, this could be merged.

**Comment by odarbelaeze** [comment]
@eyscode I can take over :shipit:

**Comment by eyscode** [comment]
@odarbelaeze I just added you as collaborator. Can you review and approve this PR? Also give me your pypi account so I can give you access there in order to create new releases. thanks ❤️

**Comment by fboaventura** [comment]
I can also help with maintenance :grin:

**Comment by eyscode** [comment]
@fboaventura I sent you an invite.

**Comment by fboaventura** [comment]
@eyscode got it, thanks! Pypi account is also `fboaventura`.  

Merging this one. :grin:

**Comment by eyscode** [comment]
@diegotolentino `v1.3.0` version that includes this new feature was released https://pypi.org/manage/project/timetracker-cli/release/1.3.0/

@fboaventura I sent you a maintainer invitation to your account at Pypi.

**Comment by fboaventura** [comment]
@eyscode got the invitation, thanks!

**Pull request merged**
